# Dump sql databases
- name: Dump all databases from {{ ansible_hostname }}
  mysql_db:
    state: dump
    name: all
    target: /home/ltdan/{{ ansible_hostname }}.{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}.sql

# Pull backup to local machine
- name: Pull file using rsync
  synchronize:
    mode: pull
    src: /home/ltdan/*.sql
    dest: /home/biff/received/
    checksum: yes
    times: yes
