# Dump sql databases
- name: Dump all databases from {{ ansible_hostname }}
  mysql_db:
    state: dump
    name: all
    target: /home/<your_user>/{{ ansible_hostname }}.{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}.sql

# Pull backup to local machine
- name: Pull file using rsync
  synchronize:
    mode: pull
    src: /home/<your_user>/*.sql
    dest: /home/<your_user>/<your_folder/
    checksum: yes
    times: yes
